#-------------------------
# ACTIVE DIRECTORY / SAMBA
#-------------------------
    - name: Samba - Desabilitando resolvconf
      file: path=/etc/init.d/resolvconf mode=0000

    - name: Samba - Parando serviços
      service: name={{ item.name }} state={{ item.state }}
      with_items:
        - { name: 'nmbd', state: 'stopped'}
        - { name: 'smbd', state: 'stopped'}

    - name: Samba - Removendo configurações antigas
      file: path=/etc/samba/{{ item }} state=absent recurse=no
      with_items:
        - "smb.conf"

############# SAMBA STANDALONE
   - name: Samba - Copia de arquivos de configuração
      copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} mode={{ item.mode }} force=yes
      with_items:
        - { src: '~/ansible-servidor/Calex/smb.conf', dest: '/etc/samba/', owner: 'root', group: 'root', mode: '644' }


############# SAMBA AD
#    - name: Kerberos - Removendo configurações antigas
#      file: path=/etc//{{ item }} state=absent recurse=no
#      with_items:
#        - "krb5.conf"
#
#    - name: Samba - Provisioning
#      command: samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL --realm={{ realm|upper }} --domain={{ dominio|upper }} --adminpass={{ ad_passwd }}
#
#    - name: Kerberos - Link para arquivo de configuração
#      file: src=/var/lib/samba/private/krb5.conf dest=/etc/krb5.conf state=link
#
#    - name: Samba - Configuracao do DNS Forwarder
#      lineinfile:
#        dest: /etc/samba/smb.conf
#        regexp: '^\tdns'
#        line: "\tdns forwarder = 8.8.8.8"
#        state: present
################################################################

    - name: Samba - Iniciando
      service: name={{ item.name }} state={{ item.state }}
      with_items:
        - { name: 'nmbd', state: 'started'}
        - { name: 'smbd', state: 'started'}
        - { name: 'samba-ad-dc', state: 'started'}



# TESTES: (tem que dar certo)
#
# host -t SRV _kerberos._udp.calex.local.br
# host -t SRV _ldap._tcp.calex.local.br
# host -t A calex.local.br

# Aqui precisa do DNS Forwarder em smb.conf apontando pra 8.8.8.8:
# host www.amazon.com
# host -t mx amazon.com
#
# kinit administrator@CALEX.LOCAL.BR
# klist
#
# smbclient -L localhost -UAdministrator
# smbclient //localhost/netlogon -UAdministrator -c 'ls'
# net rpc rights list -U administrator
# wbinfo --ping-dc
#
# ---------------------------------------
# Dar privilégio SeDiskOperatorPrivilege:
# ---------------------------------------
# net rpc rights grant "CALEX\Domain Admins" SeDiskOperatorPrivilege -U "CALEX\Administrator"
# net rpc rights list privileges SeDiskOperatorPrivilege -U "CALEX\administrator"






