---
- hosts: localhost
  remote_user: root

  
  vars_prompt:
    - name: "dominio"
      prompt: "Nome do Domínio (Ex. nome_empresa)"
      default: calex
      private: no
    - name: "realm"
      prompt: "Nome do Realm (Ex. nome_empresa.local.br)"
      default: calex.local.br
      private: no
    - name: "ad_passwd"
      prompt: "Admin Password (Tem que ter minusculas, maiusculas e numeros)"
      private: yes
    - name: "ad_ip"
      prompt: "IP do servidor AD"
      default: 192.168.2.2
    - name: "ad_mask"
      prompt: "MASK"
      default: 255.255.255.0
    - name: "ad_gw"
      prompt: "Gateway"
      default: 192.168.2.200

  
  roles:
#    - os_base
#    - ad_samba
    - dhcp
...
