---
- hosts: localhost
  remote_user: root
  gather_facts: True

  vars_prompt:
    - name: "dominio"
      prompt: "Nome do Domínio (Ex. nome_empresa)"
      default: calex
      private: no
    - name: "realm"
      prompt: "Nome do Realm (Ex. nome_empresa.local.br)"
      default: calex.local.br
      private: no
    - name: "ad_passwd"
      prompt: "Senha para o usuario Administrator (Tem que ter minusculas, maiusculas e numeros)"
      private: yes
    - name: "ad_ip"
      prompt: "IP para o servidor AD"
      private: no
      default: 192.168.2.2
    - name: "ad_mask"
      prompt: "MASK"
      private: no
      default: 255.255.255.0
    - name: "ad_gw"
      prompt: "Gateway"
      private: no
      default: 192.168.2.200

######## DHCP Server ###########
    - name: "dhcp_range_ini"
      prompt: "DHCP - Range (ip inicial)"
      private: no
      default: 192.168.2.50
    - name: "dhcp_range_end"
      prompt: "DHCP - Range (ip final)"
      private: no
      default: 192.168.2.250

  roles:
    - os_base
#    - ad_samba
    - dhcp
#    - proxy
#    - firewall
...
