#
# sudo passwd
# su
# apt install git ansible -y
# cd
# git clone https://github.com/rpires-enkel/ansible-desktop
# ansible-playbook ~/ansible-desktop/playbook_CALEX.yaml
#
# -------------------------


---
- hosts: localhost
  remote_user: root
#  vars:
#    dominio: "calex.local"
  vars_prompt:
    - name: "dominio"
      prompt: "Nome do Domínio (Ex. nome_empresa)"
      private: no
    - name: "realm"
      prompt: "Nome do Realm (Ex. nome_empresa.local.br)"
      private: no
#    - name: "ad_user"
#      prompt: "Usuario AD com permissao de ADM"
#      private: yes
    - name: "ad_passwd"
      prompt: "password"
      private: yes
  
  tasks:

  
########################
# PPA
########################
#    - name: PPA - Oracle
#      apt_repository: repo="ppa:webupd8team/java" state=present
#
#    - name: PPA - Configure Grub Customizer
#      apt_repository: repo="ppa:danielrichter2007/grub-customizer" state=present
#
#    - name: PPA - Configure Notepadqq
#      apt_repository: repo="ppa:notepadqq-team/notepadqq" state=present
#      
#    - name: Update repositories cache - apt-get update
#      apt:
#        update_cache: yes
#        cache_valid_time: 7200


########################
# FERRAMENTAS UTEIS
########################
    - name: Install common packages
      apt: pkg={{item}} state=latest
      with_items:
        - aptitude
        - axel
        - bzr
        - deja-dup
        - dos2unix
        - expect
        - fdupes
        - filezilla
        - gawk
        - gksu
        - gpm
        - grub-customizer
        - htop
        - httping
        - iftop
        - iotop
#        - lightdm-gtk-greeter
#        - lightdm-gtk-greeter-settings
        - nautilus-compare
        - nautilus-image-converter
        - nautilus-image-manipulator
        - nautilus-wipe
        - notepadqq
        - ntopng
        - ntpdate
        - openssh-server
        - openvpn
        - plank
        - python-pexpect
        - python-pip
        - synaptic
        - tmux
        - trash-cli
        - vim
        - whois
########## AD / SAMBA
        - krb5-user
        - samba
        - smbclient
        - sssd
        - ntp
#        - ldap-utils
#        - winbind
#        - dnsmasq-base PURGE



########################
# SSH Server
########################
#    - name: SSH Server - Edit sshd_config
#      lineinfile: dest=/etc/ssh/sshd_config
#        regexp='^PermitRootLogin'
#        line='PermitRootLogin yes'
#        state=present
#
#    - name: SSH Server - Restart service
#      service:
#        name: sshd
#        state: restarted

        
########################
# Oracle
########################
#    - name: Oracle - Agree to Oracle license
#      debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true
#      
#    - name: Oracle - Install Java 8
#      apt: name=oracle-java8-installer force=yes
      

########################
# CHROME
########################
#    - name: Google Chrome - Download
#      get_url:
#        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#        dest: /usr/local
#    
#    - name: Google Chrome - Install
#      apt:
#        deb: /usr/local/google-chrome-stable_current_amd64.deb


########################
# Webmin
########################
#    - name: Webmin - Download
#      get_url:
#        url: http://prdownloads.sourceforge.net/webadmin/webmin_1.840_all.deb
#        dest: /usr/local
#    
#    - name: Webmin - Install
#      apt:
#        deb: /usr/local/webmin_1.840_all.deb


########################
# TeamViewer
########################
#    - name: TeamViewer - Download
#      get_url:
#        url: https://download.teamviewer.com/download/teamviewer_i386.deb
#        dest: /usr/local/teamviewer_i386.deb
#    
#    - name: TeamViewer - Install
#      apt:
#        deb: /usr/local/teamviewer_i386.deb


########################
# APT UPGRADE
########################
#    - name: Upgrade Packages - apt-get upgrade
#      apt: upgrade=yes



########################
# ACTIVE DIRECTORY / SAMBA
########################
    - name: Samba - Desabilitando resolvconf
      file: path=/etc/init.d/resolvconf mode=0000

    - name: Samba - Parando serviços
      service: name={{ item.name }} state={{ item.state }}
      with_items:
        - { name: 'nmbd', state: 'stopped'}
        - { name: 'smbd', state: 'stopped'}

    - name: Samba - Removendo configurações
      file: path=/etc/samba/{{ item }} state=absent recurse=no
      with_items:
        - "smb.conf"

    - name: Removendo arquivos antigos
      file: path=/etc//{{ item }} state=absent recurse=no
      with_items:
        - "krb5.conf"
        - "resolv.conf"

    - name: Samba - Provisioning
      #command: samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL --realm=SAMDOM.EXAMPLE.COM --domain=SAMDOM --adminpass={{ ad_passwd }}
      command: samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL --realm={{ realm|upper }} --domain={{ domain|upper }} --adminpass={{ ad_passwd }}

    - name: Kerberos - Link para arquivo de configuração
      file: src=/var/lib/samba/private/krb5.conf dest=/etc/krb5.conf state=link

# INTERATIVO:
#Realm [04]:
# Domain [SAMDOM]:
# Server Role (dc, member, standalone) [dc]:
# DNS backend (SAMBA_INTERNAL, BIND9_FLATFILE, BIND9_DLZ, NONE) [SAMBA_INTERNAL]:
# DNS forwarder IP address (write 'none' to disable forwarding) [127.0.1.1]:
#Administrator password:
#Retype password:


    - name: resolv.conf - Criação do arquivo
      lineinfile:
        dest: /etc/resolv.conf
        create: yes
        regexp: '.*'
        line: "domain {{ realm|lower }}\nnameserver 127.0.0.1\nnameserver 8.8.8.8"
        state: present



#    - file: path=/usr/local/samba_shares/comercial state=directory mode=0770 owner=root group=comercial recurse=yes
#    - file: path=/usr/local/samba_shares/financeiro state=directory mode=0770 owner=root group=financeiro recurse=yes
#    - file: path=/usr/local/samba_shares/publico state=directory mode=0777 owner=root group=users recurse=yes

#    - name: Move hosts to /etc/hosts-bkp
#      command: mv /etc/hosts /etc/hosts-bkp
#    - name: Create /etc/hosts
#      lineinfile:
#        dest: /etc/hosts
#        create: yes
#        regexp: '.*'
#        line: "127.0.0.1\tlocalhost\n127.0.0.1\t{{ ansible_hostname }}.{{ dominio }}\t{{ ansible_hostname }}\n127.0.1.1\t{{ ansible_hostname }}\n{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}\t{{ ansible_hostname }}"
#        state: present

#    - name: Copy configuration files
#      copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} mode={{ item.mode }} force=yes
#      with_items:
# Unity - { src: '/root/CONFS/50-unity-greeter.conf', dest: '/usr/share/lightdm/lightdm.conf.d/', owner: 'root', mode: '644' }
 #       - { src: '/smiles-desktop-linux/krb5.conf', dest: '/etc/', owner: 'root', mode: '644' }
 #       - { src: '/smiles-desktop-linux/ntp.conf', dest: '/etc/', owner: 'root', mode: '644' }
 #       - { src: '/smiles-desktop-linux/smb.conf', dest: '/etc/samba/', owner: 'root', mode: '644' }
 #       - { src: '/smiles-desktop-linux/sssd.conf', dest: '/etc/sssd/', owner: 'root', mode: '600' }
 #       - { src: '/smiles-desktop-linux/common-session', dest: '/etc/pam.d/', owner: 'root',  mode: '644' }

#    - name: Restart Services
#      service: name={{ item.name }} state={{ item.state }}
#      with_items:
#        - { name: 'ntp', state: 'restarted'}
#        - { name: 'smbd', state: 'restarted'}
#        - { name: 'nmbd', state: 'restarted'}

#    - name: kinit
#      expect:
#        command: kinit Administrator
#        responses:
#          Password for Administrator@SMILES.COM.BR: 'senha'



...
