#
# Proxy
#

    - name: Install common packages
      apt: pkg={{item}} state=latest
      with_items:
        - squid
        - squidguard
        - squidguard-doc
        - apache2
        - awstats
        - c-icap
        - libicapapi-dev
        - libicapapi4-dbg
        - clamav-daemon
        - apparmor-utils

    - name: Squid stop
      service: name={{ item.name }} state={{ item.state }}
      with_items:
        - { name: 'squid', state: 'stopped'}

    - name: Squid - Download
      get_url:
        url: http://www.squid-cache.org/Versions/v3/3.5/squid-3.5.26.tar.gz
        dest: /opt

    - name: Squid - Descompactando
      unarchive: copy=no src="/opt/squid-3.5.26.tar.gz" dest="/opt"

    - name: Squid - ./configure make - make - install
      shell: "cd /opt/squid-3.5.26/ && ./configure '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=${prefix}/lib/squid3' '--srcdir=.' '--disable-maintainer-mode' '--disable-dependency-tracking' '--disable-silent-rules' 'BUILDCXXFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' '--datadir=/usr/share/squid' '--sysconfdir=/etc/squid' '--libexecdir=/usr/lib/squid' '--mandir=/usr/share/man' '--enable-inline' '--disable-arch-native' '--enable-async-io=8' '--enable-storeio=ufs,aufs,diskd,rock' '--enable-removal-policies=lru,heap' '--enable-delay-pools' '--enable-cache-digests' '--enable-icap-client' '--enable-follow-x-forwarded-for' '--enable-auth-basic=DB,fake,getpwnam,LDAP,NCSA,NIS,PAM,POP3,RADIUS,SASL,SMB' '--enable-auth-digest=file,LDAP' '--enable-auth-negotiate=kerberos,wrapper' '--enable-auth-ntlm=fake,smb_lm' '--enable-external-acl-helpers=file_userip,kerberos_ldap_group,LDAP_group,session,SQL_session,unix_group,wbinfo_group' '--enable-url-rewrite-helpers=fake' '--enable-eui' '--enable-esi' '--enable-icmp' '--enable-zph-qos' '--disable-translation' '--with-swapdir=/var/spool/squid' '--with-logdir=/var/log/squid' '--with-pidfile=/var/run/squid.pid' '--with-filedescriptors=65536' '--with-large-files' '--with-default-user=proxy' '--enable-build-info=Ubuntu linux' '--enable-linux-netfilter' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wall' 'LDFLAGS=-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security' --with-openssl --enable-ssl-crtd && make && make install"

    - name: Apache - Enable CGI mod
      command: a2enmod cgid

    - name: Apache restart
      service: name={{ item.name }} state={{ item.state }}
      with_items:
        - { name: 'apache2', state: 'restarted'}

### Crio os diretorios e arquivos necessarios
    - file: path=/var/cache/squid state=directory mode=0755 owner=proxy group=proxy recurse=yes
    - file: path=/etc/squid/ssl state=directory mode=0755 owner=proxy group=proxy recurse=yes
    - file: path=/var/lib/squidguard/db/deny state=directory mode=0755 owner=proxy group=proxy
    - file: path=/var/lib/squidguard/db/deny/domains state=touch mode=0666 owner=proxy group=proxy
    - file: path=/var/lib/squidguard/db/deny/urls state=touch mode=0666 owner=proxy group=proxy
    - file: path=/var/lib/squidguard owner=proxy group=proxy recurse=yes
    - file: path=/var/log/squidguard owner=proxy group=proxy recurse=yes
