#-------------------------
# DHCP
#-------------------------
    - name: DHCP Server - Instalacao
      apt: pkg={{item}} state=latest
      with_items:
        - isc-dhcp-server

    - name: DHCP Server - Removendo configurações antigas
      file: path=/etc/dhcp/{{ item }} state=absent recurse=no
      with_items:
        - "dhcpd.conf"

    - name: DHCP Server - Copia de arquivos de configuração
      copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} mode={{ item.mode }} force=yes
      with_items:
        - { src: '~/ansible-servidor/Calex/dhcpd.conf', dest: '/etc/dhcp/', owner: 'root', group: 'root', mode: '644' }

#    - name: Network - identificacao das interfaces
#      shell: ip link show | grep mode | sed 's/://g' | awk '{print $2}' | grep -m 1 -v lo
#      register: interface
#
#    - name: DHCP Server - configuracao da Interface
#      lineinfile:
#        dest: /etc/default/isc-dhcp-server
#        regexp: '^INTERFACES'
#        line: 'INTERFACES="{{ interface.stdout }}"'
#        state: present
#
#    - name: DHCP Server - Iniciando serviços
#      service: name={{ item.name }} state={{ item.state }}
#      with_items:
#        - { name: 'isc-dhcp-server', state: 'started'}



